/**
 * Catalogue statique MVP — 30 parcs MLB (saison 2025/2026).
 * ballparkId = String(mlbVenueId) — join direct avec mlb_schedule_daily.games.venue.id
 *
 * Facteurs offensifs : échelle 100 = neutre (approx. FanGraphs / BR).
 * centerFieldBearingDegrees : direction depuis le marbre vers le CF (0=N, 90=E).
 */

export const BALLPARK_CATALOG_SOURCE = "manual_mvp_v1";
export const BALLPARK_CATALOG_SEASON = 2025;

/** @typedef {'open'|'retractable'|'dome'} RoofType */
/** @typedef {'open'|'closed'|null} DefaultRoofState */

/**
 * @typedef {Object} BallparkSeedRow
 * @property {number} mlbVenueId
 * @property {string} key
 * @property {string} name
 * @property {string} city
 * @property {string} state
 * @property {number} teamId
 * @property {string} teamAbbreviation
 * @property {number} latitude
 * @property {number} longitude
 * @property {number|null} altitudeMeters
 * @property {string} timezone
 * @property {RoofType} roofType
 * @property {DefaultRoofState} defaultRoofState
 * @property {number|null} centerFieldBearingDegrees
 * @property {number|null} parkFactorRuns
 * @property {number|null} parkFactorHomeRuns
 * @property {number|null} parkFactorHits
 * @property {number|null} parkFactorDoubles
 * @property {number|null} leftHandedHomeRunFactor
 * @property {number|null} rightHandedHomeRunFactor
 */

/** @type {BallparkSeedRow[]} */
export const MLB_BALLPARK_SEED = [
  { mlbVenueId: 1, key: "angel_stadium", name: "Angel Stadium", city: "Anaheim", state: "CA", teamId: 108, teamAbbreviation: "LAA", latitude: 33.80019, longitude: -117.8824, altitudeMeters: 48, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 45, parkFactorRuns: 98, parkFactorHomeRuns: 95, parkFactorHits: 99, parkFactorDoubles: 98, leftHandedHomeRunFactor: 95, rightHandedHomeRunFactor: 96 },
  { mlbVenueId: 2, key: "camden_yards", name: "Oriole Park at Camden Yards", city: "Baltimore", state: "MD", teamId: 110, teamAbbreviation: "BAL", latitude: 39.283787, longitude: -76.621689, altitudeMeters: 10, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 30, parkFactorRuns: 101, parkFactorHomeRuns: 102, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 101, rightHandedHomeRunFactor: 103 },
  { mlbVenueId: 3, key: "fenway_park", name: "Fenway Park", city: "Boston", state: "MA", teamId: 111, teamAbbreviation: "BOS", latitude: 42.346456, longitude: -71.097441, altitudeMeters: 6, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 310, parkFactorRuns: 104, parkFactorHomeRuns: 95, parkFactorHits: 105, parkFactorDoubles: 110, leftHandedHomeRunFactor: 92, rightHandedHomeRunFactor: 98 },
  { mlbVenueId: 4, key: "rate_field", name: "Rate Field", city: "Chicago", state: "IL", teamId: 145, teamAbbreviation: "CWS", latitude: 41.83, longitude: -87.634167, altitudeMeters: 182, timezone: "America/Chicago", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 355, parkFactorRuns: 99, parkFactorHomeRuns: 98, parkFactorHits: 100, parkFactorDoubles: 101, leftHandedHomeRunFactor: 97, rightHandedHomeRunFactor: 99 },
  { mlbVenueId: 5, key: "progressive_field", name: "Progressive Field", city: "Cleveland", state: "OH", teamId: 114, teamAbbreviation: "CLE", latitude: 41.495861, longitude: -81.685255, altitudeMeters: 199, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 20, parkFactorRuns: 97, parkFactorHomeRuns: 96, parkFactorHits: 98, parkFactorDoubles: 97, leftHandedHomeRunFactor: 95, rightHandedHomeRunFactor: 97 },
  { mlbVenueId: 7, key: "kauffman_stadium", name: "Kauffman Stadium", city: "Kansas City", state: "MO", teamId: 118, teamAbbreviation: "KC", latitude: 39.051567, longitude: -94.480483, altitudeMeters: 260, timezone: "America/Chicago", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 40, parkFactorRuns: 98, parkFactorHomeRuns: 97, parkFactorHits: 99, parkFactorDoubles: 100, leftHandedHomeRunFactor: 96, rightHandedHomeRunFactor: 98 },
  { mlbVenueId: 14, key: "rogers_centre", name: "Rogers Centre", city: "Toronto", state: "ON", teamId: 141, teamAbbreviation: "TOR", latitude: 43.64155, longitude: -79.38915, altitudeMeters: 86, timezone: "America/Toronto", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 10, parkFactorRuns: 102, parkFactorHomeRuns: 105, parkFactorHits: 101, parkFactorDoubles: 100, leftHandedHomeRunFactor: 104, rightHandedHomeRunFactor: 106 },
  { mlbVenueId: 15, key: "chase_field", name: "Chase Field", city: "Phoenix", state: "AZ", teamId: 109, teamAbbreviation: "AZ", latitude: 33.445302, longitude: -112.066687, altitudeMeters: 331, timezone: "America/Phoenix", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 0, parkFactorRuns: 103, parkFactorHomeRuns: 104, parkFactorHits: 102, parkFactorDoubles: 101, leftHandedHomeRunFactor: 103, rightHandedHomeRunFactor: 105 },
  { mlbVenueId: 17, key: "wrigley_field", name: "Wrigley Field", city: "Chicago", state: "IL", teamId: 112, teamAbbreviation: "CHC", latitude: 41.948171, longitude: -87.655503, altitudeMeters: 182, timezone: "America/Chicago", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 355, parkFactorRuns: 101, parkFactorHomeRuns: 102, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 101, rightHandedHomeRunFactor: 103 },
  { mlbVenueId: 19, key: "coors_field", name: "Coors Field", city: "Denver", state: "CO", teamId: 115, teamAbbreviation: "COL", latitude: 39.756042, longitude: -104.994136, altitudeMeters: 1609, timezone: "America/Denver", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 5, parkFactorRuns: 115, parkFactorHomeRuns: 107, parkFactorHits: 112, parkFactorDoubles: 108, leftHandedHomeRunFactor: 106, rightHandedHomeRunFactor: 108 },
  { mlbVenueId: 22, key: "dodger_stadium", name: "Dodger Stadium", city: "Los Angeles", state: "CA", teamId: 119, teamAbbreviation: "LAD", latitude: 34.07368, longitude: -118.24053, altitudeMeters: 155, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 35, parkFactorRuns: 96, parkFactorHomeRuns: 98, parkFactorHits: 97, parkFactorDoubles: 96, leftHandedHomeRunFactor: 97, rightHandedHomeRunFactor: 99 },
  { mlbVenueId: 31, key: "pnc_park", name: "PNC Park", city: "Pittsburgh", state: "PA", teamId: 134, teamAbbreviation: "PIT", latitude: 40.446904, longitude: -80.005753, altitudeMeters: 222, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 340, parkFactorRuns: 96, parkFactorHomeRuns: 92, parkFactorHits: 97, parkFactorDoubles: 98, leftHandedHomeRunFactor: 90, rightHandedHomeRunFactor: 94 },
  { mlbVenueId: 32, key: "american_family_field", name: "American Family Field", city: "Milwaukee", state: "WI", teamId: 158, teamAbbreviation: "MIL", latitude: 43.02838, longitude: -87.97099, altitudeMeters: 203, timezone: "America/Chicago", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 130, parkFactorRuns: 99, parkFactorHomeRuns: 100, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 99, rightHandedHomeRunFactor: 101 },
  { mlbVenueId: 680, key: "t_mobile_park", name: "T-Mobile Park", city: "Seattle", state: "WA", teamId: 136, teamAbbreviation: "SEA", latitude: 47.591333, longitude: -122.33251, altitudeMeters: 5, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 55, parkFactorRuns: 92, parkFactorHomeRuns: 88, parkFactorHits: 93, parkFactorDoubles: 92, leftHandedHomeRunFactor: 86, rightHandedHomeRunFactor: 90 },
  { mlbVenueId: 2392, key: "daikin_park", name: "Daikin Park", city: "Houston", state: "TX", teamId: 117, teamAbbreviation: "HOU", latitude: 29.756967, longitude: -95.355509, altitudeMeters: 15, timezone: "America/Chicago", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 340, parkFactorRuns: 101, parkFactorHomeRuns: 105, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 104, rightHandedHomeRunFactor: 106 },
  { mlbVenueId: 2394, key: "comerica_park", name: "Comerica Park", city: "Detroit", state: "MI", teamId: 116, teamAbbreviation: "DET", latitude: 42.339115, longitude: -83.048695, altitudeMeters: 183, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 150, parkFactorRuns: 98, parkFactorHomeRuns: 97, parkFactorHits: 99, parkFactorDoubles: 100, leftHandedHomeRunFactor: 96, rightHandedHomeRunFactor: 98 },
  { mlbVenueId: 2395, key: "oracle_park", name: "Oracle Park", city: "San Francisco", state: "CA", teamId: 137, teamAbbreviation: "SF", latitude: 37.778383, longitude: -122.389448, altitudeMeters: 3, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 85, parkFactorRuns: 93, parkFactorHomeRuns: 85, parkFactorHits: 94, parkFactorDoubles: 95, leftHandedHomeRunFactor: 82, rightHandedHomeRunFactor: 88 },
  { mlbVenueId: 2523, key: "steinbrenner_field", name: "George M. Steinbrenner Field", city: "Tampa", state: "FL", teamId: 139, teamAbbreviation: "TB", latitude: 27.97997, longitude: -82.50702, altitudeMeters: 17, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 20, parkFactorRuns: 100, parkFactorHomeRuns: 100, parkFactorHits: 100, parkFactorDoubles: 100, leftHandedHomeRunFactor: 100, rightHandedHomeRunFactor: 100 },
  { mlbVenueId: 2529, key: "sutter_health_park", name: "Sutter Health Park", city: "West Sacramento", state: "CA", teamId: 133, teamAbbreviation: "ATH", latitude: 38.57994, longitude: -121.51246, altitudeMeters: 9, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 30, parkFactorRuns: 100, parkFactorHomeRuns: 100, parkFactorHits: 100, parkFactorDoubles: 100, leftHandedHomeRunFactor: 100, rightHandedHomeRunFactor: 100 },
  { mlbVenueId: 2602, key: "great_american_ball_park", name: "Great American Ball Park", city: "Cincinnati", state: "OH", teamId: 113, teamAbbreviation: "CIN", latitude: 39.097389, longitude: -84.506611, altitudeMeters: 167, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 115, parkFactorRuns: 103, parkFactorHomeRuns: 108, parkFactorHits: 102, parkFactorDoubles: 101, leftHandedHomeRunFactor: 107, rightHandedHomeRunFactor: 109 },
  { mlbVenueId: 2680, key: "petco_park", name: "Petco Park", city: "San Diego", state: "CA", teamId: 135, teamAbbreviation: "SD", latitude: 32.707861, longitude: -117.157278, altitudeMeters: 4, timezone: "America/Los_Angeles", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 350, parkFactorRuns: 92, parkFactorHomeRuns: 88, parkFactorHits: 93, parkFactorDoubles: 92, leftHandedHomeRunFactor: 86, rightHandedHomeRunFactor: 90 },
  { mlbVenueId: 2681, key: "citizens_bank_park", name: "Citizens Bank Park", city: "Philadelphia", state: "PA", teamId: 143, teamAbbreviation: "PHI", latitude: 39.905391, longitude: -75.16717, altitudeMeters: 6, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 15, parkFactorRuns: 101, parkFactorHomeRuns: 103, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 102, rightHandedHomeRunFactor: 104 },
  { mlbVenueId: 2889, key: "busch_stadium", name: "Busch Stadium", city: "St. Louis", state: "MO", teamId: 138, teamAbbreviation: "STL", latitude: 38.622567, longitude: -90.192867, altitudeMeters: 141, timezone: "America/Chicago", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 60, parkFactorRuns: 98, parkFactorHomeRuns: 96, parkFactorHits: 99, parkFactorDoubles: 98, leftHandedHomeRunFactor: 95, rightHandedHomeRunFactor: 97 },
  { mlbVenueId: 3289, key: "citi_field", name: "Citi Field", city: "Flushing", state: "NY", teamId: 121, teamAbbreviation: "NYM", latitude: 40.75753, longitude: -73.845592, altitudeMeters: 4, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 15, parkFactorRuns: 97, parkFactorHomeRuns: 94, parkFactorHits: 98, parkFactorDoubles: 97, leftHandedHomeRunFactor: 93, rightHandedHomeRunFactor: 95 },
  { mlbVenueId: 3309, key: "nationals_park", name: "Nationals Park", city: "Washington", state: "DC", teamId: 120, teamAbbreviation: "WSH", latitude: 38.872861, longitude: -77.007501, altitudeMeters: 3, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 30, parkFactorRuns: 99, parkFactorHomeRuns: 98, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 97, rightHandedHomeRunFactor: 99 },
  { mlbVenueId: 3312, key: "target_field", name: "Target Field", city: "Minneapolis", state: "MN", teamId: 142, teamAbbreviation: "MIN", latitude: 44.981829, longitude: -93.277891, altitudeMeters: 249, timezone: "America/Chicago", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 45, parkFactorRuns: 99, parkFactorHomeRuns: 98, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 97, rightHandedHomeRunFactor: 99 },
  { mlbVenueId: 3313, key: "yankee_stadium", name: "Yankee Stadium", city: "Bronx", state: "NY", teamId: 147, teamAbbreviation: "NYY", latitude: 40.829195, longitude: -73.926498, altitudeMeters: 5, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 75, parkFactorRuns: 102, parkFactorHomeRuns: 105, parkFactorHits: 101, parkFactorDoubles: 98, leftHandedHomeRunFactor: 104, rightHandedHomeRunFactor: 106 },
  { mlbVenueId: 4169, key: "loandepot_park", name: "loanDepot park", city: "Miami", state: "FL", teamId: 146, teamAbbreviation: "MIA", latitude: 25.777962, longitude: -80.219518, altitudeMeters: 2, timezone: "America/New_York", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 125, parkFactorRuns: 94, parkFactorHomeRuns: 90, parkFactorHits: 95, parkFactorDoubles: 94, leftHandedHomeRunFactor: 88, rightHandedHomeRunFactor: 92 },
  { mlbVenueId: 4705, key: "truist_park", name: "Truist Park", city: "Cumberland", state: "GA", teamId: 144, teamAbbreviation: "ATL", latitude: 33.890672, longitude: -84.467641, altitudeMeters: 308, timezone: "America/New_York", roofType: "open", defaultRoofState: null, centerFieldBearingDegrees: 160, parkFactorRuns: 100, parkFactorHomeRuns: 99, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 98, rightHandedHomeRunFactor: 100 },
  { mlbVenueId: 5325, key: "globe_life_field", name: "Globe Life Field", city: "Arlington", state: "TX", teamId: 140, teamAbbreviation: "TEX", latitude: 32.747299, longitude: -97.081818, altitudeMeters: 165, timezone: "America/Chicago", roofType: "retractable", defaultRoofState: "closed", centerFieldBearingDegrees: 45, parkFactorRuns: 101, parkFactorHomeRuns: 102, parkFactorHits: 100, parkFactorDoubles: 99, leftHandedHomeRunFactor: 101, rightHandedHomeRunFactor: 103 },
];

export function ballparkIdFromVenueId(venueId) {
  return String(venueId ?? "").trim();
}
