export const CREDIT_SOURCES = /** @type {const} */ ({
  SIGNUP_BONUS: "CREDIT_SIGNUP_BONUS",
  DAILY_SHOT: "CREDIT_DAILY_SHOT",
  PURCHASE_PACK: "CREDIT_PURCHASE_PACK",

  DEFI_ENTRY: "CREDIT_DEFI_ENTRY",
  DEFI_PAYOUT: "CREDIT_DEFI_PAYOUT",
  DEFI_REFUND: "CREDIT_DEFI_REFUND",

  ADJUSTMENT: "CREDIT_ADJUSTMENT",
  AVATAR_PURCHASE: "CREDIT_AVATAR_PURCHASE",

  STREAK3_REWARD: "CREDIT_STREAK3_REWARD",
  FIVE_PARTICIP_REWARD: "CREDIT_FIVE_PARTICIP_REWARD",

  

});